<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class LanguageTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $languages = [
            'Akan',
            'Alemannic',
            'Amharic',
            'Aragonese',
            'Arabic',
            'Aramaic',
            'Assamese',
            'Asturian',
            'Avar',
            'Aymara',
            'Azerbaijani',
            'Bashkir',
            'Bavarian',
            'Samogitian',
            'Bikol',
            'Belarusian',
            'Bulgarian',
            'Bihari',
            'Bislama',
            'Bambara',
            'Bengali',
            'Tibetan',
            'Bishnupriya',
            'Breton',
            'Bosnian',
            'Buginese',
            'Buriat',
            'Catalan',
            'Chechen',
            'Cebuano',
            'Chamorrom',
            'Choctawm',
            'Cherokeem',
            'Cheyennem',
            'Corsicanm',
            'Creem',
            'Czechm',
            'Kashubianm',
            'Chuvashm',
            'Welshm',
            'Danishm',
            'Germanm',
            'Dimlim',
            'Lowerm',
            'Divehim',
            'Dzongkham',
            'Farsim',
            'Greek',
            'English',
            'Esperanto',
            'Spanish',
            'Estonian',
            'Basque',
            'Extremaduran',
            'Peul',
            'Finnish',
            'Faroese',
            'French',
            'Arpitan',
            'Friulian',
            'Irish',
            'Garhwali',
            'Scottish',
            'Gilbertese',
            'Galician',
            'Guarani',
            'Gothic',
            'Gujarati',
            'Manxe',
            'Hausa',
            'HakkaChinese',
            'Hawaiian',
            'Hindi',
            'Croatian',
            'Haitian',
            'Hungarian',
            'Armenian',
            'Herero',
            'Interlingua',
            'Indonesian',
            'Interlingue',
            'Igbo',
            'Sichuan',
            'Inupiak',
            'Ilokano',
            'Ido',
            'Icelandic',
            'Italian',
            'Inuktitut',
            'Japanese',
            'Lojban',
            'Javanes',
            'Georgiane',
            'Kongo',
            'Kikuyu',
            'Kuanyama',
            'Kazakh',
            'Greenlandic',
            'Cambodian',
            'Kannada',
            'Khowar',
            'Korean',
            'Kanurie',
            'Kashmiri',
            'Ripuarian',
            'Kurdish',
            'Komi',
            'Cornish',
            'Kirghiz',
            'Latin',
            'Ladino',
            'Lango',
            'Luxembourgish',
            'Ganda',
            'Limburgian',
            'Ligurian',
            'Lombard',
            'Lingala',
            'Laotian',
            'Lithuanian',
            'Latvian',
        ];
 
        $i = 1;
        foreach ($languages as $language) {
            DB::table('languages')->insert([
                'id' => $i,
                'name' => $language,
                'created_at' => Carbon::now(),
            ]);

            $i++;
        }
    }
}
